// Generated by gencpp from file robot_msgs/ButtonStatus.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_BUTTONSTATUS_H
#define ROBOT_MSGS_MESSAGE_BUTTONSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct ButtonStatus_
{
  typedef ButtonStatus_<ContainerAllocator> Type;

  ButtonStatus_()
    : continue_button(false)
    , halt_button(false)
    , controller_mode_button(false)  {
    }
  ButtonStatus_(const ContainerAllocator& _alloc)
    : continue_button(false)
    , halt_button(false)
    , controller_mode_button(false)  {
  (void)_alloc;
    }



   typedef uint8_t _continue_button_type;
  _continue_button_type continue_button;

   typedef uint8_t _halt_button_type;
  _halt_button_type halt_button;

   typedef uint8_t _controller_mode_button_type;
  _controller_mode_button_type controller_mode_button;





  typedef boost::shared_ptr< ::robot_msgs::ButtonStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::ButtonStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonStatus_

typedef ::robot_msgs::ButtonStatus_<std::allocator<void> > ButtonStatus;

typedef boost::shared_ptr< ::robot_msgs::ButtonStatus > ButtonStatusPtr;
typedef boost::shared_ptr< ::robot_msgs::ButtonStatus const> ButtonStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::ButtonStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::ButtonStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::ButtonStatus_<ContainerAllocator1> & lhs, const ::robot_msgs::ButtonStatus_<ContainerAllocator2> & rhs)
{
  return lhs.continue_button == rhs.continue_button &&
    lhs.halt_button == rhs.halt_button &&
    lhs.controller_mode_button == rhs.controller_mode_button;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::ButtonStatus_<ContainerAllocator1> & lhs, const ::robot_msgs::ButtonStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ButtonStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ButtonStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ButtonStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6604d0e7e58a8aeec7fe727e398df583";
  }

  static const char* value(const ::robot_msgs::ButtonStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6604d0e7e58a8aeeULL;
  static const uint64_t static_value2 = 0xc7fe727e398df583ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/ButtonStatus";
  }

  static const char* value(const ::robot_msgs::ButtonStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool continue_button\n"
"bool halt_button\n"
"bool controller_mode_button\n"
;
  }

  static const char* value(const ::robot_msgs::ButtonStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.continue_button);
      stream.next(m.halt_button);
      stream.next(m.controller_mode_button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::ButtonStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::ButtonStatus_<ContainerAllocator>& v)
  {
    s << indent << "continue_button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.continue_button);
    s << indent << "halt_button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.halt_button);
    s << indent << "controller_mode_button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.controller_mode_button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_BUTTONSTATUS_H
