// Generated by gencpp from file robot_msgs/ButtonId.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_BUTTONID_H
#define ROBOT_MSGS_MESSAGE_BUTTONID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct ButtonId_
{
  typedef ButtonId_<ContainerAllocator> Type;

  ButtonId_()
    : continue_button(0)
    , halt_button(0)
    , controller_mode_button(0)  {
    }
  ButtonId_(const ContainerAllocator& _alloc)
    : continue_button(0)
    , halt_button(0)
    , controller_mode_button(0)  {
  (void)_alloc;
    }



   typedef int32_t _continue_button_type;
  _continue_button_type continue_button;

   typedef int32_t _halt_button_type;
  _halt_button_type halt_button;

   typedef int32_t _controller_mode_button_type;
  _controller_mode_button_type controller_mode_button;





  typedef boost::shared_ptr< ::robot_msgs::ButtonId_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::ButtonId_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonId_

typedef ::robot_msgs::ButtonId_<std::allocator<void> > ButtonId;

typedef boost::shared_ptr< ::robot_msgs::ButtonId > ButtonIdPtr;
typedef boost::shared_ptr< ::robot_msgs::ButtonId const> ButtonIdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::ButtonId_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::ButtonId_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::ButtonId_<ContainerAllocator1> & lhs, const ::robot_msgs::ButtonId_<ContainerAllocator2> & rhs)
{
  return lhs.continue_button == rhs.continue_button &&
    lhs.halt_button == rhs.halt_button &&
    lhs.controller_mode_button == rhs.controller_mode_button;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::ButtonId_<ContainerAllocator1> & lhs, const ::robot_msgs::ButtonId_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ButtonId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ButtonId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ButtonId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ButtonId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ButtonId_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ButtonId_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::ButtonId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "314a9db055f7b4a1c338114270c57aba";
  }

  static const char* value(const ::robot_msgs::ButtonId_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x314a9db055f7b4a1ULL;
  static const uint64_t static_value2 = 0xc338114270c57abaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::ButtonId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/ButtonId";
  }

  static const char* value(const ::robot_msgs::ButtonId_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::ButtonId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 continue_button\n"
"int32 halt_button\n"
"int32 controller_mode_button\n"
;
  }

  static const char* value(const ::robot_msgs::ButtonId_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::ButtonId_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.continue_button);
      stream.next(m.halt_button);
      stream.next(m.controller_mode_button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonId_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::ButtonId_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::ButtonId_<ContainerAllocator>& v)
  {
    s << indent << "continue_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.continue_button);
    s << indent << "halt_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.halt_button);
    s << indent << "controller_mode_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.controller_mode_button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_BUTTONID_H
