// Generated by gencpp from file robot_msgs/MotorSpeedCommand.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MOTORSPEEDCOMMAND_H
#define ROBOT_MSGS_MESSAGE_MOTORSPEEDCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct MotorSpeedCommand_
{
  typedef MotorSpeedCommand_<ContainerAllocator> Type;

  MotorSpeedCommand_()
    : header()
    , left(0.0)
    , right(0.0)  {
    }
  MotorSpeedCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeedCommand_

typedef ::robot_msgs::MotorSpeedCommand_<std::allocator<void> > MotorSpeedCommand;

typedef boost::shared_ptr< ::robot_msgs::MotorSpeedCommand > MotorSpeedCommandPtr;
typedef boost::shared_ptr< ::robot_msgs::MotorSpeedCommand const> MotorSpeedCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator1> & lhs, const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator1> & lhs, const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f32685125452f5bdf68130369af5296";
  }

  static const char* value(const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f32685125452f5bULL;
  static const uint64_t static_value2 = 0xdf68130369af5296ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MotorSpeedCommand";
  }

  static const char* value(const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 left\n"
"float64 right\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeedCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MotorSpeedCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MotorSpeedCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MOTORSPEEDCOMMAND_H
